### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept-lsp#10]
Like the title @orbitalquark. README.md said as simple as copy to `modules`. But `Makefile` tells there is a dependency. Btw, I think I have to rename it from init.lua to something else isn't it? Which name? Why don't it has a suitable name from the beginning?

**Comment by orbitalquark** [comment]
If you download a release, it contains all needed dependencies. Unless 
you're running the nightly version of Textadept, I recommend you 
download the module bundle released alongside Textadept. Releases from 
this project are targeted at the nightly version and may not be 
compatible with previous releases of Textadept.

**Comment by ghost** [comment]
I'm using nightly version of TextAdept. Official is stuck at 11.4 (GTK based). I don't like GTK. You switched to Qt is the reason I give TextAdept another try.

**Comment by orbitalquark** [comment]
If you're using nightly, then use the latest release from the project 
page. Is it not working?

**Comment by ghost** [comment]
> If you're using nightly, then use the latest release from the project page. Is it not working?

The latest release was from 2020!

**Comment by orbitalquark** [comment]
If you click on the "Releases" link, you'll see this note: "Latest 
automated build (ignore github-actions' release date)"

I know it's an extra click, but it's there.
