### ISSUE TITLE
How to add an unknown language server?

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept-lsp#11]
Your wiki is useless @orbitalquark: https://github.com/orbitalquark/textadept/wiki/LSP-Configurations

At least, it must be something like this:

https://github.com/lite-xl/lite-xl-lsp

Taken from their config.lua (https://github.com/lite-xl/lite-xl-lsp/blob/master/config.lua):

```
---# ccls
--- __Status__: Works
--- __Site__: https://github.com/MaskRay/ccls/
--- __Installation__: https://github.com/MaskRay/ccls/wiki
lspconfig.ccls = add_lsp {
  name = "ccls",
  language = "c/cpp",
  file_patterns = {
    "%.c$", "%.h$", "%.inl$", "%.cpp$", "%.hpp$",
    "%.cc$", "%.C$", "%.cxx$", "%.c++$", "%.hh$",
    "%.H$", "%.hxx$", "%.h++$", "%.objc$", "%.objcpp$"
  },
  command = { "ccls" },
  verbose = false
}
```

**Comment by ghost** [comment]
For example, if the language server uses a custom TCP port, how could I specify it so TextAdept could know and use this port?

**Comment by orbitalquark** [comment]
The README suggests using a function that returns a string followed by a 
configuration table (that will be converted to JSON and sent to the 
language server):

   lsp.server_commands.cpp = function()
     return 'cquery', {
       cacheDirectory = '/tmp/cquery-cache',
       compilationDatabaseDirectory = io.get_project_root(),
       progressReportFrequencyMs = -1
     }
   end

**Comment by ghost** [comment]
> For example, if the language server uses a custom TCP port, how could I specify it so TextAdept could know and use this port?

@orbitalquark How to tell TextAdept to listen to a specific port?

**Comment by orbitalquark** [comment]
You can't. This implementation operates over stdin and stdout.

**Comment by ghost** [comment]
> You can't. This implementation operates over stdin and stdout.

You should add this to README.md.
