### ISSUE TITLE
Lua LSP server doesn't start

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept-lsp#14]
I installed the LSP module in `/usr/share/textadept/modules` and the Lua LSP stopped working. 
As far as I can see, it boils down to line 10 in `init.lua`
```
io.open('server.log', 'w'):close() -- clear previous log
```
This will only work when the log is in a directory the user can write. This may not always be the case.

**Comment by orbitalquark** [comment]
Thanks for the report. Fixed via https://github.com/orbitalquark/textadept-lsp/commit/e765d5b5f0f70b4bc67518898d437e67dfef5aa5
