### ISSUE TITLE
Feature request: Code Actions support

### ISSUE THREAD

**Issue by M0JXD** [orbitalquark/textadept-lsp#24]
Hi, 

Firstly - thanks for this awesome editor.

I'm wondering if you might add "code actions" to this plugin? I've been working with Dart/Flutter of recent and they're really useful for working with the framework.

Here is how it looks in VS Code for reference:
![vscode_actions](https://github.com/user-attachments/assets/130ed5ed-2dee-4af5-8407-06917b527d7a)

Aside from VS Code the only other editor I've seen with this implemented is Kate, where it is available in a right-click menu called "Code Action".

Also, have you considered getting Textadept added to this list?: https://microsoft.github.io/language-server-protocol/implementors/tools/

Your LSP implementation is better than some others listed so I think you deserve a spot :)

**Comment by orbitalquark** [comment]
Thanks for the feedback!

I will look into adding some Code Action support when I have some time. Years ago when I wrote the majority of this LSP client, I don't think Code Action support was in the servers I used, so I had nothing to test against.

I will also consider making a PR to add to the list you linked to. I didn't have a GitHub account (nor was Textadept on GitHub) at the time I wrote the initial version of this client, so adding to that list wasn't an option for me.

How time flies...

**Comment by M0JXD** [comment]
Thanks for considering :)

I definitely think you should have it added to the list, I suppose anyone could add to the list but I think it's best coming from you as the maintainer.

I've noticed the "information warnings" from the Dart LSP seem to be causing the GTK version to freeze. I think this is due to the 64K stdout buffer limit as mentioned in the manual, but I thought you should know nonetheless.

**Comment by orbitalquark** [comment]
Basic code actions support is in https://github.com/orbitalquark/textadept-lsp/commit/51b7f90a43c386044ed32cf7de8150ccaa9caae4 and will be in the next downloadable archive and the next nightly version of Textadept.

Support is probably not going to be as extensive as in your screenshot.

I don't expect a bug-free experience, so let me know if you experience any issues. I tested it with clangd and will be able to test with gopls early next week.

**Comment by M0JXD** [comment]
Wow, super stuff! Thank you.
I'll let you know how it goes.
