### ISSUE TITLE
python lsp's not working.

### ISSUE THREAD

**Issue by ltade** [orbitalquark/textadept-lsp#25]
I tried 3 python lsp's and none of them worked, even though clangd for c/c++ worked wonders 

1. python-lsp-server (Fork of the python-language-server) installed using pacman as `pylsp` binary. version: `v1.12.0`
the lsp gets started, but `Go To Definition` <f12> function does not work. `Show logs` doesn't show any errors:
```
Starting language server: /usr/bin/pylsp
Connected to pylsp 1.12.0
```
2. python-language-server installed using `pip install python-language-server` as `pyls` binary version `0.36.2` 
also doesn't work, but `Show logs` at least gives some feedback:
```
Starting language server: /home/ade/.local/bin/pyls
Server returned an error: NotImplementedError: Python version 3.12 is currently not supported.
```
maybe `python-language-server` is deprecated? it's not clear to me, moving on.

3. pyright, installed using pacman as `pyright`, version: `1.1.389`. logs:

```
Starting language server: pyright
Unable to start LSP server: /home/ade/.textadept/modules/lsp/init.lua:466: attempt to index a nil value (local 'line')
stack traceback:
	/home/ade/.textadept/modules/lsp/init.lua:733: in metamethod 'index'
	/home/ade/.textadept/modules/lsp/init.lua:466: in method 'read'
	/home/ade/.textadept/modules/lsp/init.lua:492: in method 'request'
	/home/ade/.textadept/modules/lsp/init.lua:273: in function </home/ade/.textadept/modules/lsp/init.lua:263>
	[C]: in function 'xpcall'
	/home/ade/.textadept/modules/lsp/init.lua:731: in function 'lsp.start'
	/home/ade/.textadept/modules/lsp/init.lua:1275: in function </home/ade/.textadept/modules/lsp/init.lua:1261>
	/home/ade/tools/textadept/modules/textadept/menu.lua:538: in function </home/ade/tools/textadept/modules/textadept/menu.lua:534>
	[C]: in function 'pcall'
	/home/ade/tools/textadept/core/events.lua:422: in function 'events.emit'
	/home/ade/tools/textadept/modules/textadept/menu.lua:568: in function 'textadept.menu.select_command'
	/home/ade/tools/textadept/modules/textadept/menu.lua:175: in function 'keys.ctrl+p'
	[C]: in function 'xpcall'
	/home/ade/tools/textadept/core/keys.lua:181: in upvalue 'key_command'
	/home/ade/tools/textadept/core/keys.lua:199: in function </home/ade/tools/textadept/core/keys.lua:185>
	[C]: in function 'pcall'
	/home/ade/tools/textadept/core/events.lua:422: in function 'events.emit'
	(...tail calls...)
	[C]: in function 'pcall'
	/home/ade/tools/textadept/core/events.lua:422: in function 'events.emit'
```

Note: the `Show logs` output was tested with `lsp.log_rpc = false` settign otherwise the logs would be way too long and polluted. 
also note, I tested with textadept v12.4  build, and textadept nightly build with same results

**Comment by Adomo-Software** [comment]
Update: i found jedi-language server works fine, as long as you dont do `Go To Workspace Symobl` <shift-f12> which hangs for a long time and doesn't seem to find anything.

but this might be server problem. no idea.

**Comment by ltade** [comment]
closing issue, i'll re-check if i installed those packages correctly
