### ISSUE TITLE
Suggestion: make `goto_*` jumps partake in `textadept.history`

### ISSUE THREAD

**Issue by metaleap** [orbitalquark/textadept-lsp#3]
My current workaround for this looks like this, and works as expected:

```lua
keys['f12'] = function()
    textadept.history.record()
    lsp.goto_definition()
end
```

But would be for all your `lsp.goto_*` funcs a quite familiar default behavior I think for many users coming from the more mainstream editors... certainly vscode and sublime I can say for sure.

**Comment by orbitalquark** [comment]
This is a good idea, thanks.

**Comment by orbitalquark** [comment]
Added via https://github.com/orbitalquark/textadept-lsp/commit/8a30a089ec120cfa844f5bdb74630e6e34bd5070
